#!/bin/bash
#
#  "sv-rm" script by furryfixer which is glorified alias
#  for "rm -r /var/service/$1"
#  There is an extra check to ensure operand is given and file exists
#  The service will be halted if possible before removal

if [ -z "$1" ] || [ ! -z "$2" ]; then       
        echo "Syntax error. One and only one operand expected. "\""sv-rm A"\"
        exit 1
fi
if [ ! -e "/var/service/$1" ]; then
	echo "Error. Service "\""/var/service/"$1\"" is already missing"
	exit 1
fi

sv d $1
rm -r /var/service/$1
exit
